name: CI with Jenkinsfile Runner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Jenkinsfile
        uses: jenkinsci/jenkinsfile-runner-action@v2
        with:
          jenkinsfile: Jenkinsfile
